name: "Build and publish"
on:
  schedule:
    - cron: "0 0 1 * *" # every month at midnight
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-name: ["arch", "ubuntu"]
        hascal-version: ["latest"]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@7e0881f8fe90b25e305bbf0309761e9314607e25
        with:
          cosign-release: "v1.9.0"

      - name: Push to ghcr.io ${{matrix.hascal-version}}/${{matrix.os-name}}
        uses: docker/build-push-action@v2
        with:
          context: ${{matrix.hascal-version}}/${{matrix.os-name}}
          tags: ghcr.io/hascal/hascal-${{ matrix.os-name }}:${{matrix.hascal-version}}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
