name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - { name: "arch-latest", path:"latest/arch" }
          - { name: "ubuntu-latest", path:"latest/ubuntu" }
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image ${{ matrix.name.name }}
        run: docker build ${{matrix.name.path}} --file Dockerfile --tag my-image-name:$(date +%s)
